version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - .private/database.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    volumes:
      - ./azurite/:/workspace
    restart: unless-stopped